### ISSUE TITLE
"snarkJS: Error: Scalar size does not match"

### ISSUE THREAD

**Issue by jp4g** [iden3/snarkjs#114]
Hello,

I forked [tommymsz006's zkbattleship-circuit](/tommymsz006https://github.com/tommymsz006/zkbattleship-circuit) and am trying to get it running with circom 2.0.x along with some other qol changes (hardhat & npm cli). [Here is my implementation](https://github.com/jp4g/zkbattleship-circuit/tree/update). 

First I run `circom/setup.sh`:
```
#!/bin/bash

# exit when any command fails
set -e
# set working directory

# compile circuit
circom battleship_pedersen.circom --r1cs --wasm
# powers of tau
mkdir tau && mkdir zkey && cd tau
snarkjs powersoftau new bn128 12 pot12_0000.ptau -v
snarkjs powersoftau contribute  pot12_0000.ptau pot12_0001.ptau --name="Contribution"
snarkjs powersoftau prepare phase2 pot12_0001.ptau pot12_final.ptau -v
snarkjs groth16 setup ../battleship_pedersen.r1cs pot12_final.ptau ../zkey/battleship_pedersen_0000.zkey
snarkjs zkey contribute ../zkey/battleship_pedersen_0000.zkey ../zkey/battleship_pedersen_0001.zkey --name="Name" -v
snarkjs zkey export verificationkey ../zkey/battleship_pedersen_0001.zkey ../verification_key.json
# export to solidity
snarkjs zkey export solidityverifier ../zkey/battleship_pedersen_0001.zkey ../../contracts/Verifier.sol
```
Then I attempt to run `circom/prove.sh`:
```
#!/bin/bash

# exit when any command fails
set -e
# compute witness
cd battleship_pedersen_js
node generate_witness.js battleship_pedersen.wasm ../input.json ../witness.wtns
cd ..
# create proof
mkdir proof
snarkjs groth16 prove ./zkey/battleship_pedersen_0001.zkey witness.wtns ./proof/public.json ./proof/proof.json
# local validity check
snarkjs groth16 verify verification_key.json ./proof/public.json ./proof/proof.json
```
which fails with `[ERROR] snarkJS: Error: Scalar size does not match`

My circuit is 
```
include "../node_modules/circomlib/circuits/pedersen.circom";

template Battleship() {
    signal input carrierX;
    signal input carrierY;
    signal input carrierO;
    signal input battleshipX;
    signal input battleshipY;
    signal input battleshipO;
    signal input cruiserX;
    signal input cruiserY;
    signal input cruiserO;
    signal input submarineX;
    signal input submarineY;
    signal input submarineO;
    signal input destroyerX;
    signal input destroyerY;
    signal input destroyerO;
    signal input shipHash[2];
    signal input targetX;
    signal input targetY;
    signal output out;

    signal isInRange;
    signal isCarrierHit;
    signal isBattleshipHit;
    signal isCruiserHit;
    signal isSubmarineHit;
    signal isDestroyerHit;
    signal isHit;

    // hash check
    component hash = Pedersen(256);
    component n2b = Num2Bits(256);
    n2b.in <-- carrierX + carrierY * 16 + carrierO * (16**2) + battleshipX * (16**3) + battleshipY * (16**4) + battleshipO * (16**5) + cruiserX * (16**6) + cruiserY * (16**7) + cruiserO * (16**8) + submarineX * (16**9) + submarineY * (16**10) + submarineO * (16**11) + destroyerX * (16**12) + destroyerY * (16**13) + destroyerO * (16**14);
    for (var i = 0; i < 256; i++) {
        hash.in[i] <-- n2b.out[i];
    }
    shipHash[0] === hash.out[0];
    shipHash[1] === hash.out[1];

    // map check
    isInRange <-- (targetX >= 0 && targetX <= 9 && targetY >= 0 && targetY <= 9);
    isInRange === 1;

    // hit check
    isCarrierHit <-- (carrierO == 0 && targetX == carrierX && targetY >= carrierY && targetY <= carrierY + 4) || (carrierO == 1 && targetY == carrierY && targetX >= carrierX && targetX <= carrierX + 4);

    isBattleshipHit <-- (battleshipO == 0 && targetX == battleshipX && targetY >= battleshipY && targetY <= battleshipY + 3) || (battleshipO == 1 && targetY == battleshipY && targetX >= battleshipX && targetX <= battleshipX + 3);

    isCruiserHit <-- (cruiserO == 0 && targetX == cruiserX && targetY >= cruiserY && targetY <= cruiserY + 2) || (cruiserO == 1 && targetY == cruiserY && targetX >= cruiserX && targetX <= cruiserX + 2);

    isSubmarineHit <-- (submarineO == 0 && targetX == submarineX && targetY >= submarineY && targetY <= submarineY + 2) || (submarineO == 1 && targetY == submarineY && targetX >= submarineX && targetX <= submarineX + 2);

    isDestroyerHit <-- (destroyerO == 0 && targetX == destroyerX && targetY >= destroyerY && targetY <= destroyerY + 1) || (destroyerO == 1 && targetY == destroyerY && targetX >= destroyerX && targetX <= destroyerX + 1);

    isHit <-- (isCarrierHit || isBattleshipHit || isCruiserHit || isSubmarineHit || isDestroyerHit);
    out <== isHit;
}

component main = Battleship();
```
I believe that I have followed the directions as prescribed in #103 and am still unable to figure out where I went wrong. Perhaps the hash is different from the input.json?
```
{
	"carrierX": 1,
	"carrierY": 5,
	"carrierO": 0,
	"battleshipX": 1,
	"battleshipY": 1,
	"battleshipO": 1,
	"cruiserX": 2,
	"cruiserY": 2,
	"cruiserO": 0,
	"submarineX": 3,
	"submarineY": 3,
	"submarineO": 1,
	"destroyerX": 4,
	"destroyerY": 4,
	"destroyerO": 0,
	"shipHash": [
		"15371012960482137946917706525041309012742389477796243405444203314253192438392",
		"19031326454053382003804995623051023108909279464552768973890359122774208474629"
	],
	"targetX": 0,
	"targetY": 0
}
```

**Comment by DhairyaDesai** [comment]
hmm, interesting

**Comment by socathie** [comment]
I got the same error running the official example of "binary check" from the documentation.

**Comment by JofArnold** [comment]
You should binary search your code to find the offending line and report back. I common occurrence of this for me in the past has been within for loops if i recall correctly.

Off topic maybe I didn't know you could assign like this `thing <-- a || b`. Since Circom operates on numbers I would have assumed there would be a type mismatch. Is that a documented feature?

**Comment by jp4g** [comment]
@JofArnold I am new to circom and had forked someone else's code, but I used your advice and refactored the circuit such that input.json is 
```
{
	"ships": [
        [1, 5, 0],
        [1, 1, 1],
        [2, 2, 0],
        [3, 3, 1],
        [4, 4, 0]
    ],
    "shipHash": [
		"15371012960482137946917706525041309012742389477796243405444203314253192438392",
		"19031326454053382003804995623051023108909279464552768973890359122774208474629"
	],
	"target": [0, 0]
}
```
and my circuit is 
```
include "../node_modules/circomlib/circuits/pedersen.circom";

template ShipHit() {
    signal input target[2]; //0: x, 1: y
    signal input ship[4]; //0: x, 1: y, 2: z (ship length), 3: o (orientation)
    signal output out;

    signal horizontal;
    signal vertical;
  
    horizontal <-- (ship[3] == 0 && target[0] == ship[0] && target[1] >= ship[1] && target[1] <= ship[1] + ship[2]);
    vertical <-- (ship[3] == 1 && target[0] >= ship[0] && target[0] <= ship[0] + ship[2] && target[1] == target[1]);
    out <-- (horizontal == 1 || vertical == 1);
}

template Battleship() {
    signal input ships[5][3];
    signal input shipHash[2];
    signal input target[2];
    signal output out;
    
    signal hashCheck;
    signal isInRange;

    // hash check
    component hash = Pedersen(256);
    component n2b = Num2Bits(256);

    var num = 0;
    for (var i = 0; i < 5; i++) {
        num += ships[i][0] * (16**(i*3)) + ships[i][1] * (16**((i*3)+1)) + ships[i][2] * (16**((i*3)+2));
    }
    n2b.in <== num;
    for (var i = 0; i < 256; i++) {
        hash.in[i] <== n2b.out[i];
    }
    assert(shipHash[0] == hash.out[0] && shipHash[1] == hash.out[1]);
    
    // range check
    isInRange <-- (target[0] >= 0 && target[0] <= 9 && target[1] >= 0 && target[1] <= 9);
    assert(isInRange == 1);

    // check for hit
    component ISH[5];
    var lengths[5] = [5, 4, 3, 3, 2];
    for (var i = 0; i < 5; i++) {
        ISH[i] = ShipHit();
        ISH[i].target[0] <== target[0];
        ISH[i].target[1] <== target[1];
        ISH[i].ship[0] <== ships[i][0];
        ISH[i].ship[1] <== ships[i][1];
        ISH[i].ship[2] <== lengths[i];
        ISH[i].ship[3] <== ships[i][2];
    }
    out <-- (ISH[0].out == 1 || ISH[1].out == 1 || ISH[2].out == 1 || ISH[3].out == 1 || ISH[4].out == 1);
    log(out);
}

component main = Battleship();
```
The log statement for out indicates that the circuit evaluates input correctly during proving but it still throws an error at local verification:
Example when target is [0, 0] and should return no hit:
![image](https://user-images.githubusercontent.com/31053787/147248862-e8b15b9a-722d-4827-9336-00977d3258ee.png)
Example when target is [1, 1] and should return hit:
![image](https://user-images.githubusercontent.com/31053787/147248962-95726c87-3d11-435a-94ee-e7518737df37.png)

**Comment by jp4g** [comment]
> You should binary search your code to find the offending line and report back. A common occurrence of this for me in the past has been within for loops if i recall correctly.

I don't really know how I would go about doing this... every line in the circom file executes due to it logging. If you mean the prove.sh file, `snarkjs verify` is the offending command. Otherwise are you suggesting implementing binary searches in circom?

**Comment by jp4g** [comment]
I tried copy/ pasting in the Multiplier2 demo script
```
template Multiplier2 () {
   // Declaration of signals.
   signal input a;
   signal input b;
   signal output c;

   // Constraints.
   c <== a * b;
   log(c);
}
```
STILL getting scalar size doesn't match... doesn't seem like the issue is in the .circom circuit...

**Comment by JofArnold** [comment]
@jp4g Do you have a link to a public repo? I don't see anything obviously wrong to me at least from your posts alone.

Is there any chance you accidentally have an earlier version of circom there due to a dependency? I.e. run `yarn why circom` (or whatever the npm version is if that's what you use) within that script to see if it's definitely not present. Annoyingly lots of dependencies still importing the 0.5.x version including hardhat-circom and a few other things you might have handing around.

**Comment by jp4g** [comment]
@JofArnold https://github.com/jp4g/zkbattleship-circuit I just merged all my changes into master

**Comment by jp4g** [comment]
I have circom globally installed at 2.0.2 and no circom installed in the npm project. If I try to install it in the package it cannot find 2.0.2 only 0.5.x and below

**Comment by JofArnold** [comment]
@jp4g I'm not at my computer but one thing that strikes me; you are using a very old version of snarkjs. 0.1.x will be yours (due to the ^ not sure which exactly). The latest is 0.4.x or something.

**Comment by jp4g** [comment]
@JofArnold very much appreciate the speedy replies! Unfortunately after getting compliant with `npx npm-check-updates` the error is the same. I am going to keep dependency hunting as I may have inherited old code from the forked repo

**Comment by JofArnold** [comment]
Ok, I fixed it. There's quite a few different things going on, but in essence "clear it all out all the artefacts and run things differently". Things were being generated in the wrong order and that plus existing artefacts was making it confusing. 

I changed the setup.sh to

```bash
yarn snarkjs powersoftau new bn128 12 ./circom/pot12_0000.ptau -v
yarn snarkjs powersoftau contribute  ./circom/pot12_0000.ptau ./circom/pot12_0001.ptau --name="Contribution" -e="$(head -n 4096 /dev/urandom | openssl sha1)"
yarn snarkjs powersoftau verify ./circom/pot12_0001.ptau
yarn snarkjs powersoftau prepare phase2 ./circom/pot12_0001.ptau ./circom/pot12_final.ptau -v -e="$(head -n 4096 /dev/urandom | openssl sha1)"
yarn snarkjs powersoftau verify ./circom/pot12_final.ptau
```

and prove.sh to

```bash
circom  --r1cs --wasm --output ./circom ./circom/battleship_pedersen.circom
node ./circom/battleship_pedersen_js/generate_witness.js ./circom/battleship_pedersen_js/battleship_pedersen.wasm ./circom/input.json ./circom/witness.wtns
yarn snarkjs groth16 setup ./circom/battleship_pedersen.r1cs ./circom/pot12_final.ptau ./circom/zkey/circuit_final.key
... etc
```

Ignore the `yarn` etc. This is just a copy and paste. Main thing is the order of what's generated in first ptau versus circuit compile and second ceremony,

TIP 1: I use the `-e` flag to dynamically generate some entropy to save you typing stuff.
TIP 2: don't run your own ptaus. There's some on npm as well as projects like mine at https://github.com/JofArnold/zkp-learning-in-public/tree/main/%40projects/utils/ptau

Separately there appears to be a circom bug I'll raise a ticket for in a mo

**Comment by jp4g** [comment]
@JofArnold I have refactored again into one script `snark.sh`, and tried to remove any bloat from repo. This is my current attempt at setup -> local verification: https://github.com/jp4g/zkbattleship-circuit/blob/update/snark.sh#L6-L27
```
snarkjs powersoftau new bn128 12 ./circom/pot12_0000.ptau -v
snarkjs powersoftau contribute ./circom/pot12_0000.ptau ./circom/pot12_0001.ptau \
    --name="Contribution"    -e="$(head -n 4096 /dev/urandom | openssl sha1)"
snarkjs powersoftau verify ./circom/pot12_0001.ptau
snarkjs powersoftau prepare phase2 ./circom/pot12_0001.ptau ./circom/pot12_final.ptau \
    -v -e="$(head -n 4096 /dev/urandom | openssl sha1)"
snarkjs powersoftau verify ./circom/pot12_final.ptau
# PROVE
## compile circuit
circom --r1cs --wasm --output ./circom ./circom/battleship_pedersen.circom
## compile witness
node ./circom/battleship_pedersen_js/generate_witness.js ./circom/battleship_pedersen_js/battleship_pedersen.wasm \
    ./circom/input.json ./circom/witness.wtns
## setup groth16
snarkjs groth16 setup ./circom/battleship_pedersen.r1cs ./circom/pot12_final.ptau \
    ./circom/zkey/circuit_0000.zkey
snarkjs zkey contribute ./circom/zkey/circuit_0000.zkey ./circom/zkey/circuit_final.zkey --name="Name" \
    -v -e="$(head -n 4096 /dev/urandom | openssl sha1)"
snarkjs zkey export verificationkey ./circom/zkey/circuit_final.zkey ./circom/verification_key.json
snarkjs groth16 prove ./circom/zkey/circuit_final.zkey ./circom/witness.wtns \
    ./circom/proof/public.json ./circom/proof/proof.json
snarkjs groth16 verify ./circom/verification_key.json ./circom/proof/public.json ./circom/proof/proof.json
```
still: `Error: Scalar size does not match`. Core issue still stands :/


Entropy tip is :key:, 
> TIP 2: don't run your own ptaus if you don't have to
I should run `snarkjs zkey contribute` on someone else's ptau to make it more decentralized?

**Comment by jp4g** [comment]
Just posting the `setup.sh` and `prove.sh` that worked for me with @JofArnold's help!

Setup.sh:
```
#!/bin/sh
set -e

# --------------------------------------------------------------------------------
# Phase 1
# ... non-circuit-specific stuff

# Starts Powers Of Tau ceremony, creating the file pot12_0000.ptau
snarkjs powersoftau new bn128 12 ./circom/ptau/pot12_0000.ptau -v

# Contribute to ceremony a few times...
# As we want this to be non-interactive we'll just write something random-ish for entropy
snarkjs powersoftau contribute ./circom/ptau/pot12_0000.ptau ./circom/ptau/pot12_0001.ptau \
    --name="First contribution" -v -e="$(head -n 4096 /dev/urandom | openssl sha1)"
snarkjs powersoftau contribute ./circom/ptau/pot12_0001.ptau ./circom/ptau/pot12_0002.ptau \
    --name="Second contribution" -v -e="$(head -n 4096 /dev/urandom | openssl sha1)"
snarkjs powersoftau contribute ./circom/ptau/pot12_0002.ptau ./circom/ptau/pot12_0003.ptau \
    --name="Third contribution" -v -e="$(head -n 4096 /dev/urandom | openssl sha1)"

# Verify
snarkjs powersoftau verify ./circom/ptau/pot12_0003.ptau

# Apply random beacon to finalised this phase of the setup.
# For more information about random beacons see here: https://eprint.iacr.org/2017/1050.pdf
# For the purposes, the beacon is essentially a delayed hash function evaluated on 0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f
# (in practice this value will be some form of high entropy and publicly available data of your choice)
snarkjs powersoftau beacon ./circom/ptau/pot12_0003.ptau ./circom/ptau/pot12_beacon.ptau \
    0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f 10 -n="Final Beacon"

# Prepare phase 2...
# Under the hood, the prepare phase2 command calculates the encrypted evaluation of the Lagrange polynomials at tau for
# tau, alpha*tau and beta*tau. It takes the beacon ptau file we generated in the previous step, and outputs a final pta
# file which will be used to generate the circuit proving and verification keys.
snarkjs powersoftau prepare phase2 ./circom/ptau/pot12_beacon.ptau ./circom/ptau/pot12_final.ptau -v

# Verify the final ptau file. Creates the file pot12_final.ptau
snarkjs powersoftau verify ./circom/ptau/pot12_final.ptau
```
Prove.sh:
```
#!/bin/sh
set -e

# --------------------------------------------------------------------------------
# Phase 2
# ... circuit-specific stuff

# Compile the circuit. Creates the files:
# - circuit.r1cs: the r1cs constraint system of the circuit in binary format
# - battleship_js folder: wasm and witness tools
# - circuit.sym: a symbols file required for debugging and printing the constraint system in an annotated mode
circom ./circom/battleship.circom -o ./circom --r1cs --wasm --sym
# Optional - view circuit state info
# snarkjs r1cs info ./circom/battleship.r1cs

# Optional - print the constraints
# snarkjs r1cs print ./circom/battleship.r1cs ./circom/battleship.sym

# Optional - export the r1cs
# yarn snarkjs r1cs export json ./zk/circuit.r1cs ./zk/circuit.r1cs.json && cat circuit.r1cs.json
# or...
# yarn zk:export-r1cs

# Generate witness
node ./circom/battleship_js/generate_witness.js ./circom/battleship_js/battleship.wasm \
    ./circom/input.json ./circom/witness.wtns

# Setup (use plonk so we can skip ptau phase 2
snarkjs groth16 setup ./circom/battleship.r1cs ./circom/ptau/pot12_final.ptau ./circom/zkey/battleship_final.zkey

# Generate reference zkey
snarkjs zkey new ./circom/battleship.r1cs ./circom/ptau/pot12_final.ptau ./circom/zkey/battleship_0000.zkey

# Ceremony just like before but for zkey this time
snarkjs zkey contribute ./circom/zkey/battleship_0000.zkey ./circom/zkey/battleship_0001.zkey \
    --name="First contribution" -v -e="$(head -n 4096 /dev/urandom | openssl sha1)"
snarkjs zkey contribute ./circom/zkey/battleship_0001.zkey ./circom/zkey/battleship_0002.zkey \
    --name="Second contribution" -v -e="$(head -n 4096 /dev/urandom | openssl sha1)"
snarkjs zkey contribute ./circom/zkey/battleship_0002.zkey ./circom/zkey/battleship_0003.zkey \
    --name="Third contribution" -v -e="$(head -n 4096 /dev/urandom | openssl sha1)"

#  Verify zkey
snarkjs zkey verify ./circom/battleship.r1cs ./circom/ptau/pot12_final.ptau ./circom/zkey/battleship_0003.zkey

# Apply random beacon as before
snarkjs zkey beacon ./circom/zkey/battleship_0003.zkey ./circom/zkey/battleship_final.zkey \
    0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f 10 -n="Final Beacon phase2"

# Optional: verify final zkey
snarkjs zkey verify ./circom/battleship.r1cs ./circom/ptau/pot12_final.ptau ./circom/zkey/battleship_final.zkey

# Export verification key
snarkjs zkey export verificationkey ./circom/zkey/battleship_final.zkey ./circom/verification_key.json

# Create the proof
snarkjs groth16 prove ./circom/zkey/battleship_final.zkey ./circom/witness.wtns \
    ./circom/proof/proof.json ./circom/proof/public.json

# Verify the proof
snarkjs groth16 verify ./circom/verification_key.json ./circom/proof/public.json ./circom/proof/proof.json

# Export the verifier as a smart contract
snarkjs zkey export solidityverifier ./circom/zkey/battleship_final.zkey ./contracts/Verifier.sol
```

**Comment by bwuzhang** [comment]
I'm still getting the same error using the above `setup.sh` and `prove.sh`. See #203
